# Generated by Django 4.1.1 on 2022-10-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_orders"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="phone",
            field=models.CharField(default="", max_length=111),
        ),
        migrations.AlterField(
            model_name="orders", name="address", field=models.CharField(max_length=111),
        ),
        migrations.AlterField(
            model_name="orders", name="city", field=models.CharField(max_length=111),
        ),
        migrations.AlterField(
            model_name="orders", name="email", field=models.CharField(max_length=111),
        ),
        migrations.AlterField(
            model_name="orders", name="state", field=models.CharField(max_length=111),
        ),
        migrations.AlterField(
            model_name="orders",
            name="zip_code",
            field=models.CharField(max_length=111),
        ),
    ]
