# Generated by Django 4.1.1 on 2022-10-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_orders_phone_alter_orders_address_alter_orders_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders", name="address", field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="orders", name="city", field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name="orders", name="email", field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="orders",
            name="phone",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AlterField(
            model_name="orders", name="state", field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name="orders", name="zip_code", field=models.CharField(max_length=20),
        ),
    ]
