# Generated by Django 4.1.1 on 2022-10-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_orders_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders", name="amount", field=models.IntegerField(default=0),
        ),
    ]
